version: '3'
services:

    crawler:
        build: .docker
        volumes:
            - ./:/usr/src/app
        ports:
            - "3000:3000"
        command: sh -c "npm run crawler"
        dns:
            - 8.8.8.8
            - 208.67.222.222
            - 1.1.1.1
        user: node
        working_dir: /usr/src/app